name: Pull Request Hello World

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World! This was triggered by a Pull Request."